---

podman_service_type: container
podman_service_wants: []
podman_service_ports: []
podman_service_env: {}
podman_service_volumes: []
podman_service_user: podman
podman_service_group: "{{ podman_service_user }}"
podman_unqualified_search_registries:
  - "docker.io"
  - "quay.io"
# Pick ID that should (hopefully) never clash with others
podman_user_id: 1600987
