---

zenith_client_image_prefix: ghcr.io/stackhpc
zenith_client_image_name: zenith-client
zenith_client_image_tag: 0.6.0
zenith_client_image: "{{ zenith_client_image_prefix }}/{{ zenith_client_image_name }}:{{ zenith_client_image_tag }}"

zenith_client_wants: []

zenith_forward_to_host: 127.0.0.1

podman_service_user: podman
