---

- name: Ensure ansible-init directories exist
  file:
    path: "/etc/ansible-init/{{ item }}"
    state: directory
  loop:
    - includes
    - playbooks

- name: Install task includes
  copy:
    src: "{{ item }}"
    dest: /etc/ansible-init/includes/{{ item }}
  loop:
    - disks-configure-filesystem.yml

- name: Install ansible-init playbook
  copy:
    src: disks-playbook.yml
    # Leave some numbers for playbooks to execute before
    dest: /etc/ansible-init/playbooks/10-disks.yml
